spring:
  mongodb:
    databases:
      - mongo1
      - mongo2
      - mongo3
  datasource:
    db1:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db1-pool
    db2:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db2-pool
    db3:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db3-pool

  data:
    mongodb:
      mongo1:
        uri: mongodb://appuser:AppPassword456!@192.168.0.15:27020/secretdb?authSource=admin
        pool:
          max-size: 50
          min-size: 5
      mongo2:
        uri: mongodb://appuser:AppPassword456!@192.168.0.15:27020/secretdb?authSource=admin
        pool:
          max-size: 50
          min-size: 5
      mongo3:
        uri: mongodb://appuser:AppPassword456!@192.168.0.15:27020/secretdb?authSource=admin
        pool:
          max-size: 50
          min-size: 5

logpresso:
  logpresso1:
    base-url: http://192.168.0.15:18080
    connect-timeout-ms: 2000
    read-timeout-ms: 3000
  logpresso2:
    base-url: http://192.168.0.16:18080
    connect-timeout-ms: 2000
    read-timeout-ms: 3000
  logpresso3:
    base-url: http://192.168.0.17:18080
    connect-timeout-ms: 2000
    read-timeout-ms: 3000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
