spring:
  application:
    name: amos-service
  profiles:
    active: dev
  oracle:
    databases:
      - m14
      - m15
      - m16      

server:
  port: 8080

logpresso:
  retry:
    max-attempts: 3
    backoff-ms: 1000
