spring:
  datasource:
    m14:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db1-pool
    m15:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db2-pool
    m16:
      jdbc-url: jdbc:oracle:thin:@//192.168.0.15:1521/XEPDB1
      username: appuser
      password: app123cokekimchi7kaka
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: oracle-db3-pool
